packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  build:
    unocss: ^65.5.0
    unplugin-vue-components: ^28.1.0
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.11
    vitepress-plugin-group-icons: ^1.3.5
  cli:
    '@antfu/eslint-config': ^5.2.1
    '@antfu/ni': ^25.0.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^7.1.3
  frontend:
    '@iconify-json/svg-spinners': ^1.2.2
    '@shikijs/vitepress-twoslash': ^2.3.2
    '@unocss/reset': ^65.5.0
    '@vueuse/core': ^12.7.0
    floating-vue: ^5.2.2
    pinia: ^3.0.1
    vue: ^3.5.13
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    # vitest-package-exports: ^0.1.1
    # yaml: ^2.7.0
  types:
    '@types/node': ^24.3.0
  # utils:
  # tinyexec: ^0.3.2
  # dev:
  # prod:
